name: black

on:
  push:
    paths:
      - "**.py"

jobs:
  black:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - run: |
          python -m pip install --upgrade pip
          pip install black~=21.7b0
      - run: |
          black --check --verbose .
